{% set name = "cppy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da7413a286d5d31626ba35ed2c70ddfb033520cc81310088ba5a57d34039f604

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
    - setuptools_scm >=3.4.3
    - toml
  run:
    - python >={{ python_min }}
    - setuptools >=42

test:
  requires:
    - python {{ python_min }}
  imports:
    - cppy
  commands:
    - test -f ${SP_DIR}/cppy/include/cppy/cppy.h

about:
  home: https://github.com/nucleic/cppy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ headers for C extension development

  description: |
    A small C++ header library which makes it easier to write Python extension
    modules. The primary feature is a PyObject smart pointer which automatically
    handles reference counting and provides convenience methods for performing
    common object operations.
  doc_url: https://cppy.readthedocs.io/en/latest/
  dev_url: https://github.com/nucleic/cppy

extra:
  recipe-maintainers:
    - MatthieuDartiailh
